# Generated by Django 3.2.19 on 2023-09-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAcho', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
