# Generated by Django 3.2.19 on 2023-09-05 13:13

import appAcho.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appWelcome', '0001_initial'),
        ('appAcho', '0002_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=appAcho.models.Dynamic_upload_path)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'OTHERS'), (1, 'IMG'), (2, 'AUDIO')])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appWelcome.device')),
            ],
        ),
    ]
