# Generated by Django 3.2.19 on 2023-09-02 14:54

import appWelcome.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=64)),
                ('status', models.CharField(default='offline', max_length=10)),
                ('ip', models.CharField(max_length=20)),
                ('nick_name', models.CharField(default='Device', max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to=appWelcome.models.deviceDynamic_profile_pic_path)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authority_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, upload_to=appWelcome.models.userDynamic_profile_pic_path)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appWelcome.userauthority')),
                ('devices', models.ManyToManyField(to='appWelcome.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appWelcome.devicetype'),
        ),
    ]
